projects:
  securethebox-client:
    schemaPath: ./src/graphql/schema.graphql
    extensions:
      endpoints:
        dev: 'http://localhost:8000/graphql'
        prod: 'https://cloud-run.securethebox.us/graphql'
