language: node_js
node_js:
- node
script:
- yarn install
- yarn build
deploy:
  provider: firebase
  project: securethebox-client
  message: travis deployment to firebase hosting
  skip_cleanup: true
  token:
    secure: CZntoayN3a6FTzl8pxO8eE04OxufIAfmMtjipG1uqOmRyBCowEzeTbZnTNhkcGVqAAF5MEmHYIe3x26Zeb4cLV80cBaxLv/cDXl68oBFQDeHIms9Pahoi7Hplx2s+cL3vEsHTB2N3/6Wr7z4oSGk0xYiRdBBxv6XtQq+wDyc3FzrBRydg73XS00IYzU/ENyV9eMpfl4wePC+V8yWiI6XUfRCG38ojnhbzUU94RD4I2EreLzvGFvbYkW/BQ62bqh2F9PDEAaua4SFsYcKOx0O4YOQ7TeQRRdg1UItbXPcoHvGfAI8OpK5YId+pCQQRyHdzAECXscTIwyk0z9NcjH6Kt4q813fkn+zDzAVkYZtmKzmjm6VtP5EFJeKbtl/z1daDkjayhGIJNWl5JyqKLnt0Y4+Hfx6qXk+Ecwin5LLJ/WcFiizp61OI0ukV0RSnpvDUCmx8Nx1XSAHlRRBH8yS49fYsOhHsOaa91Dq41angBM9Ta3lbye0ofE/IvNWfz3nz+3aU5rw0CkMAfyiNgQTlgzZjimVllDPSLnU9dgDbYQ47Ykex3iWe4UmWT3tjuLPpWWdLEH21uiZrIZFoKuHNQHSEjpaV7pvtUlEhFaB7gvWaRgKsUNXQiuzoDc+ouQLq2yz8jHSDzrdvrKvSzgmIjx/u+k3e7gNhbCYvX4oMqM=
env:
  global:
  - secure: CZntoayN3a6FTzl8pxO8eE04OxufIAfmMtjipG1uqOmRyBCowEzeTbZnTNhkcGVqAAF5MEmHYIe3x26Zeb4cLV80cBaxLv/cDXl68oBFQDeHIms9Pahoi7Hplx2s+cL3vEsHTB2N3/6Wr7z4oSGk0xYiRdBBxv6XtQq+wDyc3FzrBRydg73XS00IYzU/ENyV9eMpfl4wePC+V8yWiI6XUfRCG38ojnhbzUU94RD4I2EreLzvGFvbYkW/BQ62bqh2F9PDEAaua4SFsYcKOx0O4YOQ7TeQRRdg1UItbXPcoHvGfAI8OpK5YId+pCQQRyHdzAECXscTIwyk0z9NcjH6Kt4q813fkn+zDzAVkYZtmKzmjm6VtP5EFJeKbtl/z1daDkjayhGIJNWl5JyqKLnt0Y4+Hfx6qXk+Ecwin5LLJ/WcFiizp61OI0ukV0RSnpvDUCmx8Nx1XSAHlRRBH8yS49fYsOhHsOaa91Dq41angBM9Ta3lbye0ofE/IvNWfz3nz+3aU5rw0CkMAfyiNgQTlgzZjimVllDPSLnU9dgDbYQ47Ykex3iWe4UmWT3tjuLPpWWdLEH21uiZrIZFoKuHNQHSEjpaV7pvtUlEhFaB7gvWaRgKsUNXQiuzoDc+ouQLq2yz8jHSDzrdvrKvSzgmIjx/u+k3e7gNhbCYvX4oMqM=
before_install:
- cd ./src/secrets
- openssl aes-256-cbc -K $encrypted_3d1babd16ecd_key -iv $encrypted_3d1babd16ecd_iv
  -in key.js.enc -out ./key.js -d
install:
- cd ../..
